/*
 * Realized for the course of ISPW at University of Roma Tor Vergata.
 * Claudio Pastorini, Omar Shalby and Federico Vagnoni.
 * A.A. 2014/2015
 */
package it.ispw.psv.travelagency;

/**
 * This Class create a UserAlreadyRegisteredException.
 */
public class UserAlreadyRegisteredException extends Exception {

	/**
	 * Serial auto-generated by Eclipse.
	 */
	private static final long serialVersionUID = -5625440129135197884L;

	/**
	 * Default costructor.
	 */
	public UserAlreadyRegisteredException() { 
		super();
	}

	@Override
	public String getMessage() {
		return String.format("The user is already registered!");
	} 
}