/*
 * Realized for the course of ISPW at University of Roma Tor Vergata.
 * Claudio Pastorini, Omar Shalby and Federico Vagnoni.
 * A.A. 2014/2015
 */
package it.ispw.psv.travelagency;

/**
 * This Class create a ValidateException.
 */
public class ValidateException extends Exception {
	
	/**
	 * Serial auto-generated by Eclipse.
	 */
	private static final long serialVersionUID = -468326357153605240L;
	
	/**
	 * The type of the exception, could be EmailAddress, PhoneNumber and Birthdate type.
	 */
	private ValidateType type; 
	
	/**
	 * Constructor with type.
	 * @param type the type of the exception.
	 */
	public ValidateException(ValidateType type) { 
		super();
		// Set the type of the exception
		this.type = type;
	}

	@Override
	public String getMessage() {
		return String.format("There is an error with validation of %s.", type.name());
	} 
	
	/**
	 * This method return the type of exception.
	 * @return the type of the exception.
	 */
	public ValidateType getType() {
		return this.type;
	}
}